<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <NoWarn>$(NoWarn);NU1903</NoWarn>
	  <NoWarn>$(NoWarn);NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Users\**" />
    <EmbeddedResource Remove="Users\**" />
    <None Remove="Users\**" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="FluentValidation" Version="12.1.1" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.8" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Pins\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Common\Resources\ValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValidationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Common\Resources\ValidationMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
