services:
  api:
    image: jacobs51/esthetic-api:latest
    container_name: esthetic-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
      - /var/www/esthetic-images:/app/images
    depends_on:
      - redis
    restart: unless-stopped
    network_mode: host
  web:
    image: jacobs51/esthetic-web:latest
    container_name: esthetic-web
    ports:
      - "5173:80"
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data: