name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/esthetic
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            cd backend-pinterest
            docker build -t esthetic-api .
            docker stop esthetic-api || true
            docker rm esthetic-api || true
            docker run -d \
               --name esthetic-api \
               --restart=always \
               --network=host \
               --env-file /var/www/esthetic/.env \
               -v /var/www/esthetic-images:/app/images \
               -v /var/www/esthetic/appsettings.Production.json:/app/appsettings.Production.json \
               esthetic-api

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install and build
        working-directory: frontend-pinterest
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_APP_IMAGE_URL: ${{ secrets.VITE_APP_IMAGE_URL }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        run: |
          npm install
          npm run build

      - name: Deploy frontend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend-pinterest/dist/*
          target: /var/www/max.itstep.click/
          strip_components: 2