name: Move Issue to In Progress
on:
  create:

jobs:
  move-to-progress:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number
        id: info
        run: |
          BRANCH="${{ github.event.ref }}"
          ISSUE_NUM=$(echo $BRANCH | grep -oP '^\d+')
          echo "num=$ISSUE_NUM" >> $GITHUB_OUTPUT

      - name: Move to In Progress
        if: steps.info.outputs.num != ''
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.PROJECT_TOKEN }}
          organization: "pinterest-clone-project"
          project_number: 1
          operation_mode: "custom_field"
          custom_field_name: "Status"
          custom_field_value: "In progress"
          issue_number: ${{ steps.info.outputs.num }}
